#!/bin/sh

# Standard size
# djpeg -dct float -gray ACPU-128.jpg | pamcut -left 200 -right 3050 > cropped.pgm
# ./splitter -t 3 -h 21 -v 33 'pnmnorm -wperc 15 2>&- |pnmnlfilt -0.9 0.8' < cropped.pgm

# Enlarged size
djpeg -dct float -scale 16/8 -gray ACPU-128.jpg | pamcut -left 400 -right 6100 > bigcrop.pgm
./splitter -t 3 -h 43 -v 67 'pnmnorm -wperc 15 2>&- |pnmnlfilt -0.9 0.8' < bigcrop.pgm
